---
driver:
  name: vagrant
  box_download_insecure: true
  customize:
    cpus: 2
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.4

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[owi_docker::docker_service]
      - recipe[owi_docker::docker_machine]
      - recipe[owi_docker::docker_compose]
      - recipe[owi_docker::users_to_docker_group]
    verifier:
      inspec_tests:
        - name: centos7
          path: ./test/integration/centos7/inspec
    attributes: {
      "owi_docker" : {
        "service" : {
          "default" : {
            "storage_driver": "overlay2",
            "storage_opts": [
              "overlay2.override_kernel_check=true"
            ]
          }
        }
      }
    }
