---
driver:
  name: vagrant
  provision: true
  customize:
    cpus: 1
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: centos-7

verifier:
  name: inspec

suites:
  - name: default
    run_list:
      - recipe[kernel-modules]
      - recipe[sysctl::apply]
      - recipe[owi_docker::docker_service]
      - recipe[owi_docker::docker_compose]
      - recipe[owi_docker::users_to_docker_group]
      - recipe[owi_docker::docker_image]
      - recipe[owi_docker::docker_container]
    driver:
      network:
        - ["private_network", {type: "dhcp"}]
        - ["forwarded_port", {guest: 80, host: 80, auto_correct: true}]
        - ["forwarded_port", {guest: 443, host: 443, auto_correct: true}]
    verifier:
      inspec_tests:
        - name: centos7
          path: ./test/integration/centos7/inspec
    attributes: {
      "kernel_modules": {
        "modules": {
          "br_netfilter": {
            "action": [
              "load"
            ],
            "alias": "br_netfilter",
            "onboot": true,
            "reload": true,
            "check_availability": true
          }
        }
      },
      "sysctl": {
        "ignore_error": "true",
        "params": {
          "net.bridge.bridge-nf-call-ip6tables": 1,
          "net.bridge.bridge-nf-call-iptables": 1,
          "net.ipv4.conf.all.forwarding": 1,
          "net.ipv4.ip_forward": 1,
          "net.ipv4.ip_local_port_range": "1024 65000",
          "net.ipv4.tcp_tw_reuse": "1",
          "net.ipv4.tcp_fin_timeout": "15",
          "net.core.somaxconn": "4096",
          "net.core.netdev_max_backlog": "4096",
          "net.core.rmem_max": "16777216",
          "net.core.wmem_max": "16777216",
          "net.ipv4.tcp_max_syn_backlog": "20480",
          "net.ipv4.tcp_max_tw_buckets": "400000",
          "net.ipv4.tcp_no_metrics_save": "1",
          "net.ipv4.tcp_rmem": "4096 87380 16777216",
          "net.ipv4.tcp_syn_retries": "2",
          "net.ipv4.tcp_synack_retries": "2",
          "net.ipv4.tcp_wmem": "4096 65536 16777216",
          "vm.min_free_kbytes": "65536",
          "net.netfilter.nf_conntrack_max": "262144",
          "net.netfilter.nf_conntrack_tcp_timeout_established": "86400",
          "net.ipv4.neigh.default.gc_thresh1": "8096",
          "net.ipv4.neigh.default.gc_thresh2": "12288",
          "net.ipv4.neigh.default.gc_thresh3": "16384"
        }
    },
    "owi_docker" : {
      "image" : {
        "nginx" : {
            "repo" : "nginx",
            "tag" : "1.13.8"
        }
      },
      "container" : {
        "nginx" : {
            "repo" : "nginx",
            "port" : [ "80:80", "443:443" ],
            "tag" : "1.13.8",
            "labels" : [
              "project:default",
              "software:webserver"
            ]
        }
      },
      "service" : {
        "default" : {
          "storage_driver" : "overlay2",
          "storage_opts" : [
            "overlay2.override_kernel_check=true"
          ]
        }
      }
    }
  }
