AllCops:
  DisplayCopNames: true
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
    - recipes/*.rb
  Exclude:
    - vendor/**/*
    - test/**/*
    - spec/**/*

LineLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false
