language: ruby

env:
  global:
    - machine_user=travis
    - machine_pass=travis
    - machine_port=22
    - KITCHEN_YAML=.kitchen.travis.yml

rvm:
  - 2.4.0

sudo: required
dist: trusty

before_install:
  - sudo usermod -p "`openssl passwd -1 'travis'`" travis

script:
  - bundle install
  - bundle exec rake style
  # Removing unit testing for now as Travis seems to fail hard on this
  # https://travis-ci.org/USGS-CIDA/chef-cookbook-owi-docker/builds/375022589?utm_source=github_status&utm_medium=notification
  # - bundle exec rake unit

branches:
  only:
  - master
