# frozen_string_literal: true

source 'https://rubygems.org'
gem 'berkshelf'
gem 'chefspec'
gem 'docker-api'
gem 'foodcritic'
gem 'inspec'
gem 'kitchen-inspec'
gem 'kitchen-vagrant'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'serverspec'
gem 'stove'
gem 'test-kitchen'
